version: '3.8'

services:
  db:
    image: mysql:8.1
    container_name: cysec-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: cysecdb
      MYSQL_USER: cysec
      MYSQL_PASSWORD: cysec123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: cysec-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cysecdb
      SPRING_DATASOURCE_USERNAME: cysec
      SPRING_DATASOURCE_PASSWORD: cysec123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

volumes:
  db_data:
